
### GET ALL SPARE PARTS

http://localhost:5000/api/v1/czesci HTTP/1.1
Content-Type: application/json


### GET FILTERED SPARE PARTS

GET http://localhost:5000/api/v1/czesci/pralnice/pralnica-bebnowa-o-zaladunku-czolowym/PBE-15 HTTP/1.1
content-type: application/json

### UPSERT SPARE PART

POST http://localhost:5000/api/v1/czesci/new HTTP/1.1
content-type: application/json

{
    "equipment":"pralnice",
    "type":"pralnica bębnowa o załadunku bocznym",
    "model":"PBE-30",
    "assembly":"bęben wewnętrzny",
    "name":"bęben wewnętrzny",
    "netPrice":7920
}